service: your-service-name
provider:
    name: azure
    subscriptionId: azureSubId
    servicePrincipalTenantId: azureServicePrincipalTenantId
    servicePrincipalClientId: azureServicePrincipalClientId
    servicePrincipalPassword: azureServicePrincipalPassword
    location: 'East US'
plugins:
    - serverless-azure-functions
package:
    exclude: ['node_modules/**', .gitignore, package.json, '.git/**']
functions:
    test0: {handler: handler.test, events: [{http: true, x-azure-settings: {authLevel: anonymous}}]}
